[build]
  publish = "."
  functions = "netlify/functions"

[[redirects]]
  from = "/api/shortcut/transaction"
  to = "/.netlify/functions/transaction"
  status = 200

[[redirects]]
  from = "/api/shortcut/*"
  to = "/.netlify/functions/transaction"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
